CREATE DATABASE IF NOT EXISTS sessionsdb;
USE sessionsdb;
CREATE TABLE IF NOT EXISTS php_sessions (
    id VARCHAR(128) PRIMARY KEY,
    data TEXT NOT NULL,
    last_access TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE USER IF NOT EXISTS 'php_session_user'@'%' IDENTIFIED BY 'session';
GRANT ALL PRIVILEGES ON sessionsdb.* TO 'php_session_user'@'%';
FLUSH PRIVILEGES;
